name: ''
description: ''
author: "InukaSilva"
branding:
  icon: 'square'
  color: 'black'
inputs:
  source:  # id of input
    description: 'name of directory that this is being called from'
    required: true
    default: '---'


runs:
  using: "composite"
  steps:
    - run: |
        cd ..
        git clone https://github.com/InukaSilva/FIRST-Robotics-Kickoff-Countdown
        cp ${{ inputs.source }}/README.md FIRST-Robotics-Kickoff-Countdown/README.md
        cd FIRST-Robotics-Kickoff-Countdown
        python main.py
        cd ..
        cp FIRST-Robotics-Kickoff-Countdown/README.md ${{ inputs.source }}/README.md
      shell: bash